In [1]:
import numpy as np

arr = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20],
    [21, 22, 23, 24, 25]
])

print(arr)
print(arr.shape)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
(5, 5)


In [4]:
arr[0:, 2:3] = 1 
print(arr)

[[ 1  2  1  4  5]
 [ 6  7  1  9 10]
 [11 12  1 14 15]
 [16 17  1 19 20]
 [21 22  1 24 25]]


In [7]:
arr1=np.random.randint(1,36,size=(6,6))
print(arr1)
print("ans")
print(arr1[2:5,1:4])

[[27 19 20 30 16 25]
 [ 4 19 21  3 29 21]
 [11  7 35 14 14  2]
 [ 1 32  9 15  5 30]
 [30  9 34 21 24 16]
 [27 12  9 10 26  7]]
ans
[[ 7 35 14]
 [32  9 15]
 [ 9 34 21]]


In [ ]:
arr2=np.random.randint(1,25,size=(5,5))
print(arr2)
print("answer")
print(arr2[])

In [8]:
# Create a structured array with fields 'name', 'age', and 'weight'
data_type = [('name', 'U10'), ('age', 'i4'), ('weight', 'f4')]
data = np.array([('Alice', 25, 55.5), ('Bob', 30, 85.3), ('Charlie', 20, 65.2)], dtype=data_type)
print("Original array:")
print(data)

# Sort the array by age
sorted_data = np.sort(data, order='age')
print("Sorted array by age:")
print(sorted_data)

Original array:
[('Alice', 25, 55.5) ('Bob', 30, 85.3) ('Charlie', 20, 65.2)]
Sorted array by age:
[('Charlie', 20, 65.2) ('Alice', 25, 55.5) ('Bob', 30, 85.3)]


In [2]:
import pandas as pd


In [6]:
import pandas as pd
df = pd.read_csv('data.csv')
print(df.head())
print("tails data")
print(df.tail())

          Name  Age       City         Occupation
0  Amit Sharma   28      Delhi  Software Engineer
1  Priya Verma   24     Mumbai             Doctor
2  Rahul Singh   30    Lucknow            Teacher
3  Sneha Gupta   27     Jaipur           Designer
4  Arjun Patel   35  Ahmedabad        Businessman
tails data
             Name  Age      City  Occupation
45  Akash Chauhan   28    Meerut      Driver
46  Preeti Chawla   33   Panipat  Beautician
47    Ravi Shukla   37      Rewa  Contractor
48   Pankaj Verma   34  Bareilly  Pharmacist
49    Geeta Yadav   29  Azamgarh      Tailor


In [8]:
df['Name']

0            Amit Sharma
1            Priya Verma
2            Rahul Singh
3            Sneha Gupta
4            Arjun Patel
5            Neha Kapoor
6            Vikas Yadav
7           Pooja Mishra
8              Rohit Das
9           Anjali Mehta
10        Karan Malhotra
11           Simran Kaur
12         Manish Tiwari
13          Kavita Joshi
14          Deepak Kumar
15            Shreya Sen
16         Nitin Agarwal
17           Ritu Saxena
18         Sandeep Reddy
19            Meena Iyer
20            Harsh Jain
21           Ayesha Khan
22         Gaurav Pandey
23           Nisha Arora
24           Rajesh Nair
25        Swati Kulkarni
26        Abhishek Singh
27           Divya Bhatt
28          Ramesh Gowda
29         Pallavi Desai
30    Saurabh Chatterjee
31            Ishita Roy
32           Prakash Jha
33            Tanvi Shah
34         Aditya Pillai
35           Komal Verma
36           Yash Thakur
37            Farhan Ali
38          Ritika Sinha
39             Mohan Lal


In [9]:
df


,Name,Age,City,Occupation
0,Amit Sharma,28,Delhi,Software Engineer
1,Priya Verma,24,Mumbai,Doctor
2,Rahul Singh,30,Lucknow,Teacher
3,Sneha Gupta,27,Jaipur,Designer
4,Arjun Patel,35,Ahmedabad,Businessman
5,Neha Kapoor,22,Chandigarh,Student
6,Vikas Yadav,31,Patna,Police Officer
7,Pooja Mishra,26,Varanasi,Content Writer
8,Rohit Das,29,Kolkata,Data Analyst
9,Anjali Mehta,25,Surat,HR Manager


In [10]:
df.describe()

,Age
count,50.000000
mean,30.500000
std,5.159695
min,22.000000
25%,27.000000
50%,29.500000
75%,34.000000
max,45.000000


In [1]:
import pandas as pd 


In [3]:
df= pd.read_csv("data.csv")
df.isnull()

,Name,Age,City,Occupation
0,False,False,False,False
1,False,False,False,False
2,False,False,False,False
3,False,False,False,False
4,False,False,False,False
5,False,False,False,False
6,False,False,False,False
7,False,False,False,False
8,False,False,False,False
9,False,False,False,False


In [4]:
df.isnull().sum()

Name          0
Age           0
City          0
Occupation    0
dtype: int64